name: learn-github-actions-exp-context
run-name: ${{ github.actor }} is exp context GitHub Actions
on:
  push:
    branches:
    - main
  workflow_dispatch:
  
jobs:
  example-job:
    
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Deploying to production server on branch $GITHUB_REF"
          echo ${{ github.actor }}
          echo ${{ github }}
