name: learn-github-actions-exp-context
run-name: ${{ github.actor }} is exp context GitHub Actions
on:
  push:
    branches:
    - main
  workflow_dispatch:
  
jobs:
  example-job:
    
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Deploying to production server on branch $GITHUB_REF"
          echo "github.actor"
          echo ${{ github.actor }}
          
          echo "github"
          echo ${{ github }}
          
          echo "github.action_path"
          echo ${{ github.action_path }}
          
          echo "github.action_ref"
          echo ${{ github.action_ref }}
          
          echo "github.action_repository"
          echo ${{ github.action_repository }}
          
          echo "github.action_status"
          echo ${{ github.action_status }}
          
          echo "github.actor_id"
          echo ${{ github.actor_id }}
          
          echo "github.api_url"
          echo ${{ github.api_url }}
          
          echo "github.ref"
          echo ${{ github.ref }}
          
          echo "github.env"
          echo ${{ github.env }}
          
          echo "github.event"
          echo ${{ github.event }}
          
          echo "github.event_name"
          echo ${{ github.event_name }}
          
          echo "github.event_path"
          echo ${{ github.event_path }}
          
          echo "github.graphql_url"
          echo ${{ github.graphql_url }}
          
          echo "github.head_ref"
          echo ${{ github.head_ref }}
          
          echo "github.job"
          echo ${{ github.job }}
          
          echo "github.path"
          echo ${{ github.path }}
          
          echo "github.token"
          echo ${{ github.token }}
          
          echo "github.repository_owner"
          echo ${{ github.repository_owner }}
          
          echo "github.ref_name"
          echo ${{ github.ref_name }}
          

  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
        
      - name: Dump env context
        id: github_env_step
        run: echo '${{ toJSON(env) }}'
        
      - name: Dump vars context
        id: github_vars_step
        run: echo '${{ toJSON(vars) }}'
        

        
      - name: Dump job context
        run: echo '${{ toJSON(job) }}'
        
      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'
        
      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'
        
      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'
        
      - name: Dump matrix context
        id: github_matrix_step
        run: echo '${{ toJSON(matrix) }}'          
        
      - name: Dump needs context
        run: echo '${{ toJSON(needs) }}'        
