name: Build and deploy
on: 
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build_id: ${{ steps.build_step.outputs.build_id }}
    steps:
      - uses: actions/checkout@v3
      - run: echo "my build is completed {{ $$BUILD_ID }}"
      - run: echo "build_id=$BUILD_ID" >> $GITHUB_OUTPUT
      - run: echo "$$GITHUB_OUTPUT   and $$build_id"
