name: github-variables
run-name: github variables

on:
  push:
    branches:
      - main
   
jobs:
  example-job:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - run: |
          if [ "$sandeep" == "prod_env_secrets" ]
          then
            echo "got secrets"
          fi  
        env:
          sandeep: ${{ secrets.PROD_ENV_SECRETS }}

