name: github-variables
run-name: github variables

on:
  push:
    branches:
      - main
   
jobs:
  example-job:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - run: |
          if [ ${{ secrets.CANDY_SECRET }} == "cany" ]
          then
            echo "got Environment secrets ${{ secrets.PROD_ENV_SECRETS }}"
            echo "got Environment variables ${{ vars.PROD_VAR_SECRETS }}"
            echo "Repository variables ${{ vars.SANDEEP_REPO_NAME }}"
            echo "Repository secrets ${{ secrets.CANDY_SECRET }}"
          fi  
        env:
          sandeep: ${{ secrets.CANDY_SECRET }}

