name: github-variables
run-name: github variables

on:
  push:
    branches:
      - main
   
jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - run: |
          if [ "$sandeep" == "candy" ]
          then
            echo "got secrets"
          fi  
        env:
          sandeep: ${{ secrets.CANDY_SECRET }}

